version: '2'

services:
  rtorrent:
    image: vaeyo/rtorrent
    container_name: rtorrent
    restart: always
    ports:
      - 3000:3000
      - 6881:6881/udp
      - 8080:80
      - 50000:5000
    volumes:
      - ./config:/config
      - /downloads:/downloads
    environment:
      PUID:-gid-
      PGID:-uid-
      TZ:-tz-
